# Generated by Django 2.0.4 on 2018-04-30 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x509', models.TextField(help_text='PEM of the signed certificate')),
                ('serial', models.CharField(help_text='Serial number of the certificate as an hex string', max_length=100)),
                ('subject', models.CharField(help_text='Subject of this certificate', max_length=255)),
                ('valid_from', models.DateTimeField(help_text='The certificate is valid from this date')),
                ('valid_to', models.DateTimeField(help_text='The certificate is valid until this date')),
            ],
            options={
                'verbose_name': 'Issued certificates',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject of this certificate request', max_length=255)),
                ('csr', models.TextField(help_text='CSR for this request in PEM format')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revoked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='When the certificate was revoked')),
                ('reason', models.SmallIntegerField(choices=[(1, 'unspecified'), (2, 'keyCompromise'), (3, 'CACompromise'), (4, 'affiliationChanged'), (5, 'superseded'), (6, 'cessationOfOperation'), (7, 'certificateHold')], default=1)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='web.Certificate')),
            ],
            options={
                'verbose_name': 'Revoked certificates',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this certificate template', max_length=100)),
                ('days', models.SmallIntegerField(help_text='Number of days that this certificate will be valid for')),
                ('enabled', models.BooleanField(help_text='Whether this template will be available for end users')),
                ('version', models.IntegerField(help_text='Version of this certificate')),
                ('min_bits', models.PositiveSmallIntegerField(default=2048, help_text='Minimum key size')),
                ('basic_constraints', models.CharField(default="{'ca':0, 'pathlen':0}", help_text='CA cert indication and pathlen', max_length=50)),
                ('key_usage', models.TextField(blank=True, verbose_name='KeyUsage')),
                ('ext_key_usage', models.TextField(blank=True, verbose_name='ExtendedKeyUsage')),
                ('crl_points', models.TextField(blank=True, help_text='Inherited from the signing certificate/system configuration', verbose_name='CRL Distribution Points')),
                ('aia', models.TextField(blank=True, help_text='Inherited from the signing certificate/system configuration', verbose_name='Authority Info Access')),
                ('extensions', models.TextField(help_text='Other extensions for this certificate')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='csr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Request'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.Template'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
