# Generated by Django 2.0.4 on 2018-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='auto_sign',
            field=models.BooleanField(default=True, help_text='Certificates using this template will automatically be signed by the CA'),
        ),
    ]
