# Generated by Django 2.0.4 on 2018-05-01 10:25

from django.db import migrations, models
import webca.web.validators


class Migration(migrations.Migration):

    replaces = [('web', '0004_auto_20180501_1213'), ('web', '0005_auto_20180501_1217'), ('web', '0006_auto_20180501_1224')]

    dependencies = [
        ('web', '0003_auto_20180430_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved',
            field=models.NullBooleanField(default=None, help_text='Has this request been (auto)approved?'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Processing'), (2, 'Issued'), (3, 'Rejected')], default=1, help_text='Status of this request'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='x509',
            field=models.TextField(help_text='PEM of the signed certificate', validators=[webca.web.validators.valid_pem_cer]),
        ),
        migrations.AlterField(
            model_name='request',
            name='csr',
            field=models.TextField(help_text='CSR for this request in PEM format', validators=[webca.web.validators.valid_pem_csr]),
        ),
        migrations.AlterField(
            model_name='template',
            name='extensions',
            field=models.TextField(blank=True, help_text='Other extensions for this certificate'),
        ),
        migrations.AlterField(
            model_name='template',
            name='min_bits',
            field=models.PositiveSmallIntegerField(default=2048, help_text='Minimum key size', validators=[webca.web.validators.valid_key_size_number]),
        ),
        migrations.AlterField(
            model_name='template',
            name='version',
            field=models.IntegerField(default=1, help_text='Version of this certificate'),
        ),
    ]
