# Generated by Django 2.0.4 on 2018-05-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180501_1213_squashed_0006_auto_20180501_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reject_reason',
            field=models.CharField(blank=True, help_text='Why this request has been rejected', max_length=250),
        ),
    ]
