# Generated by Django 2.0.4 on 2018-05-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_request_reject_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Issued certificate'},
        ),
        migrations.AlterModelOptions(
            name='revoked',
            options={'verbose_name': 'Revoked certificate'},
        ),
        migrations.AlterField(
            model_name='template',
            name='basic_constraints',
            field=models.CharField(default='{"ca":0, "pathlen":0}', help_text='CA cert indication and pathlen', max_length=50),
        ),
    ]
