# Generated by Django 2.0.4 on 2018-05-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180501_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='version',
            field=models.IntegerField(default=1, help_text='Version of this template'),
        ),
    ]
