# Generated by Django 2.0.4 on 2018-05-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180502_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revoked',
            name='certificate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Certificate'),
        ),
        migrations.AlterField(
            model_name='template',
            name='days',
            field=models.PositiveSmallIntegerField(help_text='Number of days that this certificate will be valid for'),
        ),
    ]
