# Generated by Django 2.0.4 on 2018-05-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('web', '0009_auto_20180502_1846'), ('web', '0010_auto_20180502_1848')]

    dependencies = [
        ('web', '0008_auto_20180502_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='san_type',
            field=models.SmallIntegerField(choices=[(1, 'Hidden'), (2, 'Shown')], default=1, help_text='Require Subject Alternative Name'),
        ),
        migrations.AddField(
            model_name='template',
            name='required_subject',
            field=models.SmallIntegerField(choices=[(1, 'Full Distinguished Name'), (2, 'Common Name'), (3, 'E-Mail address')], default=2, help_text='Type of subject required: Full DN, CN, emailAddress'),
        ),
    ]
