# Generated by Django 2.0.4 on 2018-05-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180502_1846_squashed_0010_auto_20180502_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='required_subject',
            field=models.SmallIntegerField(choices=[(2, 'Common Name'), (3, 'E-Mail address'), (1, 'Full Distinguished Name'), (4, 'Partial Distinguished Name')], default=2, help_text='Type of subject required: Full or partial DN, CN or emailAddress'),
        ),
        migrations.AlterField(
            model_name='template',
            name='san_type',
            field=models.SmallIntegerField(choices=[(1, 'Hidden'), (2, 'Shown')], default=1, help_text='Require Subject Alternative Name', verbose_name='SAN Type'),
        ),
    ]
