# Generated by Django 2.0.4 on 2018-05-03 18:47

from django.db import migrations
import webca.web.fields


class Migration(migrations.Migration):

    # replaces = [('web', '0011_template_allowed_san'), ('web', '0012_auto_20180503_2043')]

    dependencies = [
        ('web', '0010_auto_20180502_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='allowed_san',
            field=webca.web.fields.SubjectAltNameField(choices=[('None', 'None'), ('DNS', 'DNS'), ('IP', 'IP'), ('URI', 'URI'), ('email', 'E-Mail'), ('UTF8', 'UTF8 String')], default='None', help_text='Allowed SAN keywords', max_length=250, verbose_name='Allowed SAN'),
        ),
    ]
