# Generated by Django 2.0.4 on 2018-05-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_template_allowed_san'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='User groups allowed to use this Template', to='auth.Group'),
        ),
    ]
