# Generated by Django 2.0.4 on 2018-05-04 12:00

from django.db import migrations, models
import webca.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_template_group_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='days',
            field=models.PositiveSmallIntegerField(help_text='Number of days that this certificate will be valid for', validators=[webca.web.validators.max_days]),
        ),
    ]
