# Generated by Django 2.0.4 on 2018-05-04 17:39

from django.db import migrations, models
import webca.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20180504_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='pathlen',
            field=models.SmallIntegerField(default=-1, help_text="Max path validation length. Only makes sense if Basic Constraints is CA.\n        If value is -1, it won't be included in the certfiicate.", validators=[webca.web.validators.valid_pathlen]),
        ),
        migrations.AlterField(
            model_name='template',
            name='basic_constraints',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Certification Authority'), (2, 'End Entity')], default=2, help_text='Type of certificate'),
        ),
    ]
