# Generated by Django 2.0.4 on 2018-05-04 19:02

from django.db import migrations
import webca.web.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_basic_constraints_pathlen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='key_usage',
            field=webca.web.fields.KeyUsageField(choices=[('digitalSignature', 'digitalSignature'), ('nonRepudiation', 'nonRepudiation'), ('keyEncipherment', 'keyEncipherment'), ('dataEncipherment', 'dataEncipherment'), ('keyAgreement', 'keyAgreement'), ('keyCertSign', 'keyCertSign'), ('cRLSign', 'cRLSign'), ('encipherOnly', 'encipherOnly'), ('decipherOnly', 'decipherOnly')], default='digitalSignature', max_length=250, verbose_name='KeyUsage'),
        ),
    ]
