# Generated by Django 2.0.4 on 2018-05-04 19:23

from django.db import migrations, models
import webca.web.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_multi_key_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='ext_key_usage_critical',
            field=models.BooleanField(default=False, verbose_name='Make the ExtendendedKeyUsage extension critical'),
        ),
        migrations.AlterField(
            model_name='template',
            name='ext_key_usage',
            field=webca.web.fields.ExtendedKeyUsageField(blank=True, choices=[('serverAuth', 'serverAuth'), ('clientAuth', 'clientAuth'), ('codeSigning', 'codeSigning'), ('emailProtection', 'emailProtection'), ('timeStamping', 'timeStamping'), ('OCSPSigning', 'OCSPSigning'), ('ipsecIKE', 'ipsecIKE'), ('msCodeInd', 'msCodeInd'), ('msCodeCom', 'msCodeCom'), ('msCTLSign', 'msCTLSign'), ('msEFS', 'msEFS')], default='None', max_length=250, verbose_name='ExtendedKeyUsage'),
        ),
        migrations.AlterField(
            model_name='template',
            name='ext_key_usage',
            field=webca.web.fields.ExtendedKeyUsageField(blank=True, choices=[('serverAuth', 'serverAuth'), ('clientAuth', 'clientAuth'), ('codeSigning', 'codeSigning'), ('emailProtection', 'emailProtection'), ('timeStamping', 'timeStamping'), ('OCSPSigning', 'OCSPSigning'), ('ipsecIKE', 'ipsecIKE'), ('msCodeInd', 'msCodeInd'), ('msCodeCom', 'msCodeCom'), ('msCTLSign', 'msCTLSign'), ('msEFS', 'msEFS')], max_length=250, null=True, verbose_name='ExtendedKeyUsage'),
        ),
    ]
