# Generated by Django 2.0.4 on 2018-05-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_multi_ext_key_usage_critical'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='san',
            field=models.TextField(blank=True, help_text='Alternative Names requested', verbose_name='SAN names'),
        ),
    ]
