# Generated by Django 2.0.4 on 2018-05-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_request_san'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRLLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL for this location')),
                ('deleted', models.BooleanField(default=False, help_text='Has this URL been deleted?')),
                ('certificates', models.ManyToManyField(help_text='Certificates using this location', to='web.Certificate')),
            ],
        ),
    ]
