# Generated by Django 2.0.4 on 2018-05-13 16:56

from django.db import migrations, models
import webca.web.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_crl_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crllocation',
            options={'verbose_name': 'CRL Location'},
        ),
        migrations.AlterField(
            model_name='template',
            name='allowed_san',
            field=webca.web.fields.SubjectAltNameField(choices=[('None', 'None'), ('DNS', 'DNS'), ('IP', 'IP'), ('URI', 'URI'), ('email', 'E-Mail'), ('UTF8', 'UTF8 String')], default='None', help_text='Allowed SAN keywords. Any number of keywords is allowed.', max_length=250, verbose_name='Allowed SAN'),
        ),
        migrations.AlterField(
            model_name='template',
            name='auto_sign',
            field=models.BooleanField(default=True, help_text='Certificate requests using this template will automatically be signed by the CA'),
        ),
        migrations.AlterField(
            model_name='template',
            name='required_subject',
            field=models.SmallIntegerField(choices=[(2, 'Common Name'), (3, 'User (CN + E-Mail)'), (1, 'Full Distinguished Name'), (4, 'Partial Distinguished Name')], default=2, help_text='Type of subject required (which fields are required in requests):<br/>\n        - CN: Common Name.<br/>\n        - User: CN + email. The email will be added as rfc822Name in the SubjectAltName extension.<br/>\n        - Full DN: All fields of the DN are required (C, ST, L, O, OU).<br/>\n        - Partial DN: CN is required, the rest are optional.'),
        ),
        migrations.AlterField(
            model_name='template',
            name='san_type',
            field=models.SmallIntegerField(choices=[(1, 'Hidden'), (2, 'Shown')], default=1, help_text='Show the Subject Alternative Name field', verbose_name='Show SAN'),
        ),
    ]
