# Generated by Django 2.0.4 on 2018-05-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_template_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Internal messages about this request'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Processing'), (2, 'Issued'), (3, 'Rejected'), (4, 'Error')], default=1, help_text='Status of this request'),
        ),
    ]
