# Generated by Django 2.0.4 on 2018-05-15 21:48

from django.db import migrations, models
import webca.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_request_admin_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='min_bits',
            new_name='min_bits_rsa',
        ),
        migrations.AlterField(
            model_name='template',
            name='min_bits_dsa',
            field=models.PositiveSmallIntegerField(default=1024, help_text='Minimum DSA key size', validators=[webca.web.validators.valid_key_size_number], verbose_name='DSA Key size'),
        ),
        migrations.AlterField(
            model_name='template',
            name='min_bits_ec',
            field=models.PositiveSmallIntegerField(default=256, help_text='Minimum Elliptic Curves (EC) key size', validators=[webca.web.validators.valid_key_size_number], verbose_name='EC Key size'),
        ),
        migrations.AlterField(
            model_name='template',
            name='min_bits_rsa',
            field=models.PositiveSmallIntegerField(default=2048, help_text='Minimum RSA key size', validators=[webca.web.validators.valid_key_size_number], verbose_name='RSA Key size'),
        ),
    ]
