# Generated by Django 2.0.4 on 2018-05-18 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0023_auto_20180517_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='One-time login code', max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ca_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
