# Generated by Django 2.0.4 on 2018-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_ca_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='causer',
            name='keys',
            field=models.TextField(blank=True, help_text='Public keys'),
        ),
    ]
