# Generated by Django 2.0.4 on 2018-05-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_causer_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='causer',
            options={'verbose_name': 'User profile'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='serial',
            field=models.CharField(db_index=True, help_text='Serial number of the certificate as an hex string', max_length=100),
        ),
    ]
