# Generated by Django 2.0.4 on 2018-04-29 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certstore_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keypair',
            name='keys',
        ),
        migrations.AddField(
            model_name='keypair',
            name='key_type',
            field=models.CharField(choices=[(6, 'RSA'), (116, 'DSA')], default=6, max_length=3),
        ),
        migrations.AddField(
            model_name='keypair',
            name='private_key',
            field=models.TextField(default='', help_text='Private key in PEM format'),
        ),
        migrations.AddField(
            model_name='keypair',
            name='public_key',
            field=models.TextField(blank=True, help_text='Public key in PEM format. Might be blank.'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.TextField(help_text='Certificate in PEM format'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='ext_key_usage',
            field=models.TextField(blank=True, verbose_name='ExtendedKeyUsage'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='key_usage',
            field=models.TextField(blank=True, verbose_name='KeyUsage'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='keys',
            field=models.ForeignKey(help_text='Key pair associated with this certificate', on_delete=django.db.models.deletion.CASCADE, to='certstore_db.KeyPair'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='serial',
            field=models.CharField(help_text='Serial number of the certificate as an hex string', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='subject',
            field=models.TextField(help_text='Subject as a distinguished name'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='valid_from',
            field=models.DateTimeField(help_text='The certificate is valid from this date'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='valid_to',
            field=models.DateTimeField(help_text='The certificate is valid until this date'),
        ),
        migrations.AlterField(
            model_name='keypair',
            name='name',
            field=models.CharField(help_text='Display name for this key pair', max_length=255),
        ),
    ]
