# Generated by Django 2.0.4 on 2018-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this object', max_length=100)),
                ('value', models.TextField(help_text='Value of this object')),
            ],
        ),
    ]
