# Generated by Django 2.0.4 on 2018-05-01 20:35

from django.db import migrations, models
import webca.config.models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationobject',
            options={'verbose_name': 'Parameter'},
        ),
        migrations.AlterField(
            model_name='configurationobject',
            name='name',
            field=models.CharField(default=webca.config.models.gen_uuid, help_text='Name of this object', max_length=100, unique=True),
        ),
    ]
