# Generated by Django 2.0.4 on 2018-04-29 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.TextField()),
                ('subject', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('serial', models.CharField(max_length=100)),
                ('key_usage', models.TextField(blank=True)),
                ('ext_key_usage', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.TextField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='keys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certstore_db.KeyPair'),
        ),
    ]
