# Generated by Django 2.0.4 on 2018-04-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certstore_db', '0003_auto_20180429_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='basic_contraints',
            new_name='basic_constraints',
        ),
    ]
