# Generated by Django 2.0.4 on 2018-04-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certstore_db', '0004_auto_20180429_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='ext_key_usage',
            field=models.TextField(blank=True, verbose_name='Extended Key Usage'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='key_usage',
            field=models.TextField(blank=True, verbose_name='Key Usage'),
        ),
    ]
