# Generated by Django 2.0.4 on 2018-05-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certstore_db', '0005_auto_20180430_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypair',
            name='key_type',
            field=models.CharField(choices=[('rsa', 'RSA'), ('dsa', 'DSA'), ('ec', 'EC')], default='rsa', max_length=3),
        ),
    ]
