# Generated by Django 2.0.4 on 2018-05-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certstore_db', '0006_add_ca_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypair',
            name='key_type',
            field=models.IntegerField(choices=[(1, 'RSA'), (2, 'DSA'), (3, 'EC')], default=1),
        ),
    ]
